version: '3.7'
services:
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    hostname: redis
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      ENV: development
    volumes:
      - ./backend:/backend
    depends_on:
      - redis
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3002:3002"
    volumes:
      - ./frontend:/frontend
