version: '3.7'
services:
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    hostname: redis
  app:
    container_name: app
    build:
      context: ./
    restart: always
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
    depends_on:
      - redis
