name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - name: "Install deno"
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.2.0
      
      - name: "Create env variables"
        shell: bash
        run: |
          cd backend
          mkdir .env
          cd .env
          echo "APP_NAME=DenoSeed
          IP=0.0.0.0
          HOST=localhost
          PORT=5000
          PROTOCOL=http
          CLIENT_PROTOCOL=http
          CLIENT_HOST=localhost
          CLIENT_PORT=3002
          REDIS_HOST=redis
          REDIS_PORT=6379
          DB_HOST=${{ secrets.DB_HOST }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASS=${{ secrets.DB_PASS }}
          EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASS=${{ secrets.EMAIL_PASS }}" > .env.test
            
      - name: "Test backend"
        shell: bash
        run: |
          cd backend
          deno test --unstable --allow-all
